# Copyright The Marin Authors
# SPDX-License-Identifier: Apache-2.0

"""External requirements generated by ``config/update-external.py``.

Do not edit this file directly. External project revisions come from their
``config/external/<name>/uv.lock`` files, the promoted GPU vLLM release comes
from ``config/external/vllm/gpu.toml``, and TPU serving requirements
come from the root ``uv.lock``.
"""

from dataclasses import dataclass
from types import MappingProxyType


@dataclass(frozen=True)
class ExternalDependency:
    """An external distribution installed from an immutable Git revision."""

    config_name: str
    distribution: str
    repository: str
    version: str
    commit: str
    runtime_requirements: tuple[str, ...]

    def requirement(self, extras: tuple[str, ...] = ()) -> str:
        """Return a PEP 508 requirement for this revision."""
        distribution = self.distribution
        if extras:
            distribution = f"{distribution}[{','.join(extras)}]"
        return f"{distribution} @ git+{self.repository}@{self.commit}"


@dataclass(frozen=True)
class VllmGpuWheel:
    """One architecture-specific wheel from a promoted vLLM GPU release."""

    architecture: str
    sm_targets: tuple[str, ...]
    url: str
    sha256: str


@dataclass(frozen=True)
class VllmGpuRelease:
    """Immutable artifacts and ABI for a promoted vLLM GPU release."""

    release_tag: str
    source_commit: str
    version: str
    torch_backend: str
    torch_version: str
    wheels: tuple[VllmGpuWheel, ...]


CUDA_TOOLCHAIN_VERSION_BY_BACKEND = MappingProxyType(
    {
        "cu130": "13.0.88",
        "cu132": "13.2.86",
    }
)


EVALCHEMY = ExternalDependency(
    config_name="evalchemy",
    distribution="evalchemy",
    repository="https://github.com/marin-community/evalchemy.git",
    version="0.1.0",
    commit="ae362881cf53f869a6ad52c8a59fa17343c0b5f8",
    runtime_requirements=(),
)

HARBOR = ExternalDependency(
    config_name="harbor",
    distribution="harbor",
    repository="https://github.com/marin-community/harbor.git",
    version="0.8.1",
    commit="a0f7a57d577080e7a78c742d79111d6ab5894355",
    runtime_requirements=("daytona==0.200.2", "gcsfs==2026.7.0", "pydantic-settings==2.14.2", "s3fs==2026.7.0"),
)

MARIN_SKYRL = ExternalDependency(
    config_name="MarinSkyRL",
    distribution="marinskyrl",
    repository="https://github.com/marin-community/MarinSkyRL.git",
    version="0.1.0",
    commit="188c7ecc6aec9f503ea422a66e6c8404f413e07a",
    runtime_requirements=(),
)

VLLM_GPU_RELEASE = VllmGpuRelease(
    release_tag="marin-vllm-gpu-20260924-01911be34fac",
    source_commit="01911be34fac8715347962a8d791ca34a879e01e",
    version="0.0.0.dev20260924+marin.01911be34fac.cu132",
    torch_backend="cu132",
    torch_version="2.13.0+cu132",
    wheels=(
        VllmGpuWheel(
            architecture="aarch64",
            sm_targets=("10.0",),
            url=(
                "https://github.com/marin-community/vllm/releases/download/"
                "marin-vllm-gpu-20260924-01911be34fac/vllm-0.0.0.dev20260924%2Bmarin.01911be34fac.cu132-"
                "cp38-abi3-manylinux_2_28_aarch64.whl"
            ),
            sha256="55724f215fc85099047785098d5d8df4e46a9eb1baeb37c36471e78d15bdb813",
        ),
        VllmGpuWheel(
            architecture="x86_64",
            sm_targets=("9.0",),
            url=(
                "https://github.com/marin-community/vllm/releases/download/"
                "marin-vllm-gpu-20260924-01911be34fac/vllm-0.0.0.dev20260924%2Bmarin.01911be34fac.cu132-"
                "cp38-abi3-manylinux_2_28_x86_64.whl"
            ),
            sha256="d04fa6af4a7161f8995154cbdbbc8dddc61b9a9ff198b3947985b2d998ef60e0",
        ),
    ),
)

VLLM_FORK_REQUIREMENT = "vllm @ git+https://github.com/marin-community/vllm.git@70ea9ae8f2601f06d820ee9d70e3afbdc52683b1"
TPU_INFERENCE_FORK_REQUIREMENT = (
    "tpu-inference @ git+https://github.com/marin-community/tpu-inference.git@29548fbab663b7ea946546ca7efaa473dab55ba5"
)

EXTERNAL_DEPENDENCIES = (
    EVALCHEMY,
    HARBOR,
    MARIN_SKYRL,
)
